Realtime kit
muxable/rtkit pull request #2
Opened 2022-06-20 18:02 UTC by varshini2402

2022-06-20 18:39 UTC, kevmo314 commented
@juaoose can you review this PR?

2022-06-20 21:53 UTC, juaoose requested changes
There are also some conventions that you could check by running `flutter analyze`, most of them are very minor.

2022-06-20 21:53 UTC, juaoose commented on remote/lib/main.dart
> +  var myMenuItems = <String>[
Shouldn't this be final? Considering its a stateless widget.

2022-06-30 14:22 UTC, juaoose approved these changes
As we discussed, try to work on the conventions and analyzer warnings on the next PRs :)

2022-07-14 14:04 UTC, juaoose commented on remote/lib/alert.dart
> +class Class3 extends StatelessWidget {
Probably better to also name this class with something more meaningful.

2022-07-14 14:31 UTC, juaoose commented on remote/lib/main.dart
> +void main() => runApp(MyApp());
Could we remove this commented code?

2022-07-25 14:05 UTC, juaoose requested changes

2022-07-25 14:05 UTC, juaoose commented on functions/src/index.ts
> +    if(doc === undefined){
I think for the document you would need to do `!doc.exists`, the undefined assignment I believe is the bevahior for `document.get("fieldName")`.

2022-07-25 14:05 UTC, juaoose commented on functions/src/index.ts
> +    res.status(200).send(doc);
This should be executed after you check that the document exists and has data, and its probably better to only return the data of the doc: `res.status(200).send(doc.data());`

2022-07-25 18:21 UTC, kevmo314 commented
Can the function changes also be pulled out into a separate pull request?

2022-07-29 15:58 UTC, juaoose commented on remote/lib/settings.dart
> +            buildNotificationOptionRow("Confirm before streaming", true),
I guess we could remove these items we don't use, but we can do that in another PR.

2022-07-29 16:08 UTC, juaoose commented on remote/lib/operations.dart
> +                onPressed: () async {
The dialog should also be dismissed when "Yes" is selected.

2022-07-29 16:20 UTC, juaoose commented on remote/lib/alert.dart
> +class Alert extends StatelessWidget {
I believe this class is not being used, we can remove it.

2022-07-29 16:33 UTC, juaoose approved these changes
Left some commets we can address in a new PR since this is one is too big already.

Also, I think you could simplify the "uuid" and "url" management, I think we don't really need to store the full URL when read from the QR code and just assume "https://kit.rtirl.com/api/" is our base. This way we could always just store an UUID and remove some code from the operations file.

2022-08-01 14:31 UTC, merged